#!/bin/sh
CONF=/etc/config/qpkg.conf
QPKG_NAME="aliyunpan"
QPKG_ROOT=`/sbin/getcfg $QPKG_NAME Install_Path -f ${CONF}`

killall aliyunpanconfig > /dev/null 2>&1
./aliyunpanconfig >&1 & 

echo "aliyunpan version is:"
./aliyundrive-webdav -V

while true ; do

pid=$(pidof "aliyundrive-webdav")
token=$(cat $QPKG_ROOT/configs/aliyunpan-config.json | jq -r '.token')
send=$(cat $QPKG_ROOT/configs/aliyunpan-config.json | jq -r '.send')
  if [[ -z "$pid" ]] && [[ -n "$token" ]] && [[ "$send" == "0" ]]; then

		port=$(cat $QPKG_ROOT/configs/aliyunpan-config.json | jq -r '.port')
		user=$(cat $QPKG_ROOT/configs/aliyunpan-config.json | jq -r '.user')
		pwd=$(cat $QPKG_ROOT/configs/aliyunpan-config.json | jq -r '.pwd')
		cache_size=$(cat $QPKG_ROOT/configs/aliyunpan-config.json | jq -r '.cache_size')
		rb_size=$(cat $QPKG_ROOT/configs/aliyunpan-config.json | jq -r '.rb_size')
  
    echo `date '+%T'` "aliyunpan try running"

	./aliyundrive-webdav -I -p $port -U $user -W $pwd -r $token -S $rb_size --cache-size $cache_size | tee $QPKG_ROOT/configs/log.txt

  fi
  echo `date '+%T'` "sleep 20s"
  sleep 20
done
