#!/bin/sh
#string:token-->{print $1},port-->2,user-->3,pwd-->4,cache_size-->5,rb_size-->6,bark-->7,send-->8,change-->9
CONF=/etc/config/qpkg.conf
QPKG_NAME="aliyunpan"
QPKG_ROOT=`/sbin/getcfg $QPKG_NAME Install_Path -f ${CONF}`

killall -9 aliyunpanconfig > /dev/null 2>&1
./aliyunpanconfig >&1 & 

echo "aliyunpan version is:"
./aliyundrive-webdav -V

while true ; do

pid=$(pidof "aliyundrive-webdav")
token=$(cat $QPKG_ROOT/configs/aliyunpan-config.json | awk -F '[,]' '{print $1}' | awk -F '["]' '{print $4}')
send=$(cat $QPKG_ROOT/configs/aliyunpan-config.json | awk -F '[,]' '{print $8}' | awk -F '["]' '{print $4}')

  if [[ -z "$pid" ]] && [[ -n "$token" ]] && [[ "$send" == "0" ]]; then

port=$(cat $QPKG_ROOT/configs/aliyunpan-config.json | awk -F '[,]' '{print $2}' | awk -F '["]' '{print $4}')
user=$(cat $QPKG_ROOT/configs/aliyunpan-config.json | awk -F '[,]' '{print $3}' | awk -F '["]' '{print $4}')
pwd=$(cat $QPKG_ROOT/configs/aliyunpan-config.json | awk -F '[,]' '{print $4}' | awk -F '["]' '{print $4}')
cache_size=$(cat $QPKG_ROOT/configs/aliyunpan-config.json | awk -F '[,]' '{print $5}' | awk -F '["]' '{print $4}')
rb_size=$(cat $QPKG_ROOT/configs/aliyunpan-config.json | awk -F '[,]' '{print $6}' | awk -F '["]' '{print $4}')	
  
    echo `date '+%T'` "aliyunpan try running"

	./aliyundrive-webdav -I -p $port -U $user -W $pwd --refresh-token $token --read-buffer-size $rb_size --cache-size $cache_size | tee $QPKG_ROOT/configs/log.txt

  fi
  echo `date '+%T'` "sleep 20s"
  sleep 20
done
